service: rail-baron-alexa-skill

frameworkVersion: 1.32.0

custom:
   defaultRegion: us-east-1
   defaultEnvironmentGroup: prd
   region: ${opt:region, self:custom.defaultRegion}
   stage: ${opt:stage, env:USER}
   environmentGroup: ${opt:environmentGroup, self:custom.defaultEnvironmentGroup}
   objectPrefix: '${self:service}-${self:custom.stage}'
   alexa:
      vendorId: ${env:AMAZON_VENDOR_ID}
      clientId: ${env:AMAZON_CLIENT_ID}
      clientSecret: ${env:AMAZON_CLIENT_SECRET}
      skills:
         -
            id: ${env:ALEXA_SKILL_ID}
            manifest:
               publishingInformation:
                  locales:
                     en-US:
                        name: rail-baron
               apis:
                  custom:
                     endpoint:
                        uri: arn:aws:lambda:${self:custom.region}:${env:AWS_ACCOUNT_ID}:function:${self:custom.objectPrefix}
               manifestVersion: '1.0'
            models:
               en-US:
                  interactionModel:
                     languageModel:
                        invocationName: rail baron
                        types:
                           -
                              name: ArticleType
                              values:
                                 - { name: { value: a, synonyms: [ an ] } }
                           -
                              name: OddOrEven
                              values:
                                 - { name: { value: odd } }
                                 - { name: { value: even } }
                           -
                              name: Region
                              values:
                                 - { name: { value: Northeast } }
                                 - { name: { value: Southeast } }
                                 - { name: { value: North Central } }
                                 - { name: { value: South Central } }
                                 - { name: { value: Plains } }
                                 - { name: { value: Northwest } }
                                 - { name: { value: Southwest } }
                        intents:
                           -
                              name: RollRegionIntent
                              slots:
                                 -
                                    name: regionNumber
                                    type: AMAZON.NUMBER
                                 -
                                    name: regionOddOrEven
                                    type: OddOrEven
                                 -
                                    name: article
                                    type: ArticleType
                              samples:
                                 - '{regionNumber} {regionOddOrEven}'
                                 - '{article} {regionNumber} {regionOddOrEven}'
                                 - 'I rolled {article} {regionNumber} {regionOddOrEven}'
                           -
                              name: ChangeRegionIntent
                              slots:
                                 -
                                    name: rolledDestinationRegion
                                    type: Region
                                 -
                                    name: destinationRegion
                                    type: Region
                              samples:
                                 - 'I am already in the {rolledDestinationRegion} I want to go to the {destinationRegion}'
                           -
                              name: RollCityIntent
                              slots:
                                 -
                                    name: cityNumber
                                    type: AMAZON.NUMBER
                                 -
                                    name: cityOddOrEven
                                    type: OddOrEven
                                 -
                                    name: article
                                    type: ArticleType
                              samples:
                                 - '{cityNumber} {cityOddOrEven}'
                                 - '{article} {cityNumber} {cityOddOrEven}'
                                 - 'I rolled {article} {cityNumber} {cityOddOrEven}'
                     dialog:
                        intents:
                           -
                              name: RollRegionIntent
                              confirmationRequired: false
                              slots:
                                 -
                                    name: regionNumber
                                    type: AMAZON.NUMBER
                                    elicitationRequired: false
                                    confirmationRequired: false
                                 -
                                    name: regionOddOrEven
                                    type: OddOrEven
                                    elicitationRequired: false
                                    confirmationRequired: false
                           -
                              name: ChangeRegionIntent
                              confirmationRequired: false
                              slots:
                                 -
                                    name: rolledDestinationRegion
                                    type: Region
                                    elicitationRequired: false
                                    confirmationRequired: false
                                 -
                                    name: destinationRegion
                                    type: Region
                                    elicitationRequired: false
                                    confirmationRequired: false
                           -
                              name: RollCityIntent
                              confirmationRequired: false
                              slots:
                                 -
                                    name: cityNumber
                                    type: AMAZON.NUMBER
                                    elicitationRequired: false
                                    confirmationRequired: false
                                 -
                                    name: cityOddOrEven
                                    type: OddOrEven
                                    elicitationRequired: false
                                    confirmationRequired: false

plugins:
   - serverless-alexa-skills

provider:
   name: aws
   runtime: nodejs6.10
   stackTags: # STAGE is automatically added by SLS
      CODE_VERSION: ${file(../node_modules/silvermine-serverless-utils/src/get-code-version.js):both}
      SLS_SVC_NAME: ${self:service}
      ENV_GROUP: ${self:custom.environmentGroup}
   deploymentBucket: root-resources-${self:custom.region}-${self:custom.environmentGroup}-deploys
   region: ${self:custom.region}
   stage: ${self:custom.stage}
   environment:
      CODE_VERSION: ${file(../node_modules/silvermine-serverless-utils/src/get-code-version.js):both}
      SLS_SVC_NAME: ${self:service}
      SLS_STAGE: ${self:custom.stage}

functions:
   skill:
      name: '${self:custom.objectPrefix}'
      handler: src/Skill.handler
      memorySize: 128
      timeout: 1
      events:
         - alexaSkill: ${env:ALEXA_SKILL_ID}
