service: rail-baron-alexa-skill

frameworkVersion: 1.32.0

custom:
   defaultRegion: us-east-1
   defaultEnvironmentGroup: prd
   region: ${opt:region, self:custom.defaultRegion}
   stage: ${opt:stage, env:USER}
   environmentGroup: ${opt:environmentGroup, self:custom.defaultEnvironmentGroup}
   objectPrefix: '${self:service}-${self:custom.stage}'
   alexa:
      vendorId: ${env:AMAZON_VENDOR_ID}
      clientId: ${env:AMAZON_CLIENT_ID}
      clientSecret: ${env:AMAZON_CLIENT_SECRET}
      skills:
         -
            id: ${env:ALEXA_SKILL_ID}
            manifest:
               publishingInformation:
                  locales:
                     en-US:
                        name: Rail Baron Assistant
                        summary: 'Provides destinations and payout information for the Avalon Hill Rail Baron game.'
                        examplePhrases:
                           - 'Alexa, tell Rail Baron I rolled a 10 odd'
                           - 'Alexa, tell Rail Baron 6 even in the Northeast'
                           - 'Alexa, ask Rail Baron how much I make between Seattle and Philadelphia'
                        keywords: [ 'rail', 'baron', 'train', 'game', 'destination', 'dice', 'roll', 'avalon', 'hill', 'payout' ]
                        # TODO: icons here?
                        description: >
                           If you play Rail Baron, you know what a PAIN it is to look up
                           destination regions and cities and the payout between them, and
                           how much that slows down your game play. Why do that when Alexa
                           can do it for you?

                           For example, here's an interaction you can have with Alexa when
                           you use Rail Baron Assistant:

                            * You: Alexa, play Rail Baron
                            * Alexa: Let's play some Rail Baron! What did you roll?
                            * You: 10 odd
                            * Alexa: You rolled a 10 odd. You're going to the Northeast.
                              What did you roll for a city? For example, "I rolled a four
                              odd in the Northeast"
                            * You: Six even in the Northeast.
                            * Alexa: You rolled a 6 even in the Northeast. You're going to Philadelphia.
                            * You: Alexa, ask Rail Baron how much from Portland, Maine to Philadelphia?
                            * Alexa: You will make $4500 from Portland, Maine to Philadelphia

                           Or, ask her simple questions each time you need, like this:

                            * Alexa, tell Rail Baron I rolled a 10 odd
                            * Alexa, tell Rail Baron 6 even in the Northeast
                            * Alexa, ask Rail Baron how much I make between Seattle and Philadelphia
               apis:
                  custom:
                     endpoint:
                        uri: arn:aws:lambda:${self:custom.region}:${env:AWS_ACCOUNT_ID}:function:${self:custom.objectPrefix}
               manifestVersion: '1.0'
            models:
               en-US:
                  interactionModel:
                     languageModel:
                        invocationName: rail baron
                        types:
                           -
                              name: ArticleType
                              values:
                                 - { name: { value: a, synonyms: [ an ] } }
                           -
                              name: OddOrEven
                              values:
                                 - { name: { value: odd } }
                                 - { name: { value: even } }
                           -
                              name: Region
                              values: ${file(./src/list-names-for-model.js):regions}
                           -
                              name: City
                              values: ${file(./src/list-names-for-model.js):cities}
                        intents:
                           -
                              name: AMAZON.CancelIntent
                              samples: []
                           -
                              name: AMAZON.HelpIntent
                              samples: []
                           -
                              name: AMAZON.StopIntent
                              samples: []
                           -
                              name: RollRegionIntent
                              slots:
                                 -
                                    name: rolledNumber
                                    type: AMAZON.NUMBER
                                 -
                                    name: rolledOddOrEven
                                    type: OddOrEven
                                 -
                                    name: article
                                    type: ArticleType
                              samples:
                                 - '{rolledNumber} {rolledOddOrEven}'
                                 - '{article} {rolledNumber} {rolledOddOrEven}'
                                 - 'I rolled {article} {rolledNumber} {rolledOddOrEven}'
                                 - 'What region is {rolledNumber} {rolledOddOrEven}'
                                 - 'What region {rolledNumber} {rolledOddOrEven} is'
                           -
                              name: RollCityIntent
                              slots:
                                 -
                                    name: rolledNumber
                                    type: AMAZON.NUMBER
                                 -
                                    name: rolledOddOrEven
                                    type: OddOrEven
                                 -
                                    name: region
                                    type: Region
                                 -
                                    name: article
                                    type: ArticleType
                              samples:
                                 - '{rolledNumber} {rolledOddOrEven} in the {region}'
                                 - '{article} {rolledNumber} {rolledOddOrEven} in the {region}'
                                 - 'I rolled {article} {rolledNumber} {rolledOddOrEven} in the {region}'
                                 - 'What city is {rolledNumber} {rolledOddOrEven} in the {region}'
                                 - 'What city {rolledNumber} {rolledOddOrEven} is in the {region}'
                           -
                              name: PayoutIntent
                              slots:
                                 -
                                    name: originCity
                                    type: City
                                 -
                                    name: destinationCity
                                    type: City
                              samples:
                                 - 'How much from {originCity} to {destinationCity}'
                                 - 'How much I make from {originCity} to {destinationCity}'
                                 - 'How much do I make from {originCity} to {destinationCity}'
                                 - 'How much is paid from {originCity} to {destinationCity}'
                                 - 'What is the pay from {originCity} to {destinationCity}'
                                 - 'What the pay is from {originCity} to {destinationCity}'
                                 - 'What the payout is from {originCity} to {destinationCity}'
                                 - 'Money from {originCity} to {destinationCity}'
                                 - 'Payout from {originCity} to {destinationCity}'
                                 # all the same phrases, but "between X and Y" instead of
                                 # "from X to Y"
                                 - 'How much between {originCity} and {destinationCity}'
                                 - 'How much I make between {originCity} and {destinationCity}'
                                 - 'How much do I make between {originCity} and {destinationCity}'
                                 - 'How much is paid between {originCity} and {destinationCity}'
                                 - 'What is the pay between {originCity} and {destinationCity}'
                                 - 'What the pay is between {originCity} and {destinationCity}'
                                 - 'What the payout is between {originCity} and {destinationCity}'
                                 - 'Money between {originCity} and {destinationCity}'
                                 - 'Payout between {originCity} and {destinationCity}'

plugins:
   - serverless-alexa-skills

provider:
   name: aws
   runtime: nodejs8.10
   stackTags: # STAGE is automatically added by SLS
      CODE_VERSION: ${file(../node_modules/silvermine-serverless-utils/src/get-code-version.js):both}
      SLS_SVC_NAME: ${self:service}
      ENV_GROUP: ${self:custom.environmentGroup}
   deploymentBucket: root-resources-${self:custom.region}-${self:custom.environmentGroup}-deploys
   region: ${self:custom.region}
   stage: ${self:custom.stage}
   environment:
      CODE_VERSION: ${file(../node_modules/silvermine-serverless-utils/src/get-code-version.js):both}
      SLS_SVC_NAME: ${self:service}
      SLS_STAGE: ${self:custom.stage}

functions:
   skill:
      name: '${self:custom.objectPrefix}'
      handler: src/Skill.handler
      memorySize: 128
      timeout: 1
      events:
         - alexaSkill: ${env:ALEXA_SKILL_ID}
